[package]
name = "opensubtitle-wasm"
version = "0.1.0"
authors = ["leokraken <joleocl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.73"